#!/bin/bash

git diff --cached --name-only | while read FILE; do
if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
    if [[ -f $FILE ]]; then
        php -l "$FILE" 1> /dev/null
        if [ $? -ne 0 ]; then
            echo -e "\e[1;31m\tAborting commit due to files with syntax errors.\e[0m" >&2
            exit 1
        fi
    fi
fi
done || exit $?

if [ $? -eq 0 ]; then
    /home/aman/.composer/vendor/bin/phpcs --standard=//home/aman/.composer/vendor/drupal/coder/coder_sniffer/Drupal "$FILE" 1> /dev/null
        if [ $? -ne 0 ]; then
            echo -e "\e[1;33m\tWarning, some files do not respecting the Drupal coding standards. Commit was not aborted.\e[0m" >&2
        fi

        RESULT=$(grep "dpm(" "$FILE")
        if [ ! -z $RESULT ]; then
            echo -e "\e[1;33m\tWarning, the commit contains a call to dpm(). Commit was not aborted, however.\e[0m" >&2
        fi
    
fi